---
language:        python
python:          "2.7"

# Use the new container infrastructure
sudo:            required

services:
  - docker

env:
  - distribution: centos
    version:     7
  - distribution: fedora
    version:     26
  - distribution: fedora
    version:     25
  - distribution: fedora
    version:     24
  - distribution: ubuntu
    version:     xenial
  - distribution: ubuntu
    version:     trusty
  - distribution: debian
    version:     stretch
  - distribution: debian
    version:     jessie

before_install:
  - 'sudo docker pull ${distribution}:${version}'
  # - 'sudo docker build --no-cache --rm --file=travis/Dockerfile.${distribution}-${version} --tag=${distribution}-${version}:ansible travis'

script:
  - container_id=$(mktemp)
  - 'sudo docker run --detach --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro --volume="${PWD}":/etc/ansible/roles/ansible-base:ro ${distribution}-${version} > "${container_id}"'
  - 'sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -v /etc/ansible/roles/ansible-base/test/test.yml --syntax-check'
  - 'sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -v /etc/ansible/roles/ansible-base/test/test.yml'
  - 'sudo docker rm -f "$(cat ${container_id})"'

notifications:
  webhooks:      https://galaxy.ansible.com/api/v1/notifications/
